server:
  port: 9999
spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848

#  redis:
#    host: redis-server
#    port: 6380
#    password: Chufhulong1999